# Site settings
title: ErintLabs OÜ
email: info@mail.erint.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_username: erintlabs
github_username: ErintLabs

# Build settings
markdown: kramdown

# Setting language flags
# https://sylvain.durand.tf/making-jekyll-multilingual/ refer to this
defaults:
  -
    scope:
      path: uk
    values:
      lang: uk
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      path: fr
    values:
      lang: fr
  -
    scope:
      path: ru
    values:
      lang: ru
