# Site settings
title: ErintLabs OÜ
email: info@mail.erint.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_username: erintlabs
github_username: ErintLabs

# Build settings
markdown: kramdown

# Setting language flags
# https://sylvain.durand.tf/making-jekyll-multilingual/ refer to this
defaults:
  -
    scope:
      path: uk
    values:
      lang: uk
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      path: fr
    values:
      lang: fr
  -
    scope:
      path: ru
    values:
      lang: ru

# Translations table
# TODO: is there a way to make it a separate file pretty please?
# WARNING: for typographic discipline reasons, single quotation marks are NOT
# to be used like apostrophes. If your keyboard lacks the respective glyph,
# here you are I have a free Unicode apostrophe right for you: ’
t:
  en:
    page_head:          'Erint Labs OÜ — software + science = ❤'
    about_who_head:     'Who we are'
    about_who_text:     'Erint Labs is a team of science and software experts, mainly having a bioinformatics background. We see ourselves as the bricklayers and the architects for the bridge to connect unsolved problems to evergrowing computational abilities of the Internet.'
    about_what_head:    'Our goals'
    about_what_text:    'We are brought together by a vision of becoming pioneers in the novel fields where science, economy and administration all face a dire need of software expertise. We think the world would make good use of more computer ingenuity applied to both emerging and unorthodox areas.'
    about_how_head:     'Our culture'
    about_how_text:     'We strongly believe in Open Source and the post-industrial decentralisation of production and research.'
    about_where_head:   'Our locations'
    about_where_text:   'We are delocalised like an electron, but are mostly affiliated with the following locations:'
    what_we_do_head:    'What we can do'
    contact_head:       'Let’s Get In Touch!'
    contact_txt:        'Are you puzzled with an issue that needs computational cracking? Do you have an interesting project you would love to outsource? Don’t hesitate to contact us:'
    logo_alt:           'ErintLabs Logo'
    big_head:           'Your bioinformatics & biotechnology partner'
    ui_more_info:       'Find Out More'
    ui_nav_toggle:      'Toggle navigation'
    ui_about:           'About'
    ui_services:        'Services'
    ui_team:            'Our team'
    ui_contact:         'Contact'
    service_head:       'Our Research Focus'
    service_it_head:    'Code meets Science'
    service_it_txt:     'The scientific world routinely produces more data than a human being is able to interpret in their head, creating a demand for multi-disciplinary developers who would relieve the headache of explaining one’s research to a computer.'
    service_lab_head:   'Custom Lab Equipment'
    service_lab_txt:    'What if a spectral analyser didn’t cost a fortune? Would you like to produce your own pippettes from recycled sources? How about fitting the equipment to your needs and taste instead of adapting to the gear’s own limitations?'
    service_auto_head:  'Internet of Efficiency'
    service_auto_txt:   'A surprising amount of organisations, governments and individuals around would accomplish more throughput while cutting a huge deal of waste should their activities use more tools that modern computer science ecosystem has to offer.'
    service_pbr_head:   'Bio-Photo-Reactors'
    service_pbr_txt:    'When encased in isolated modular cubicles and put to work, the tiny algae have shown a great promise to help the world get off fossil fuel needle, sequester greenhouse gases from the atmosphere and encourage localisation of energy production.'
    team_head:          'Get to know'
    team_txt:           'our team'
    company_name_code:  'Erint Labs OÜ, 14034333'
    company_address1:   '6 Sepapaja Str.'
    company_address2:   'Tallinn, EE-15551'
    company_address3:   'ESTONIA'
    ukraine:            'Kyiv, Ukraine'
    estonia:            'Tallinn, Estonia'
    france:             'Nice, France'
  uk:
    page_head:          '~'
    about_who_head:     '~'
    about_who_text:     '~'
    about_what_head:    '~'
    about_what_text:    '~'
    about_how_head:     '~'
    about_how_text:     '~'
    about_where_head:   '~'
    about_where_text:   '~'
    what_we_do_head:    '~'
    contact_head:       '~'
    contact_txt:        '~'
    logo_alt:           '~'
    big_head:           '~'
    ui_more_info:       '~'
    ui_nav_toggle:      '~'
    ui_about:           '~'
    ui_services:        '~'
    ui_team:            '~'
    ui_contact:         '~'
    service_head:       '~'
    service_it_head:    '~'
    service_it_txt:     '~'
    service_lab_head:   '~'
    service_lab_txt:    '~'
    service_auto_head:  '~'
    service_auto_txt:   '~'
    service_pbr_head:   '~'
    service_pbr_txt:    '~'
    team_head:          '~'
    team_txt:           '~'
    company_name_code:  'ТОВ «Erint Labs OÜ», 14034333'
    company_address1:   'вул. Сепапая, буд. 6'
    company_address2:   'м. Таллінн, EE-15551'
    company_address3:   'ЕСТОНІЯ'
    ukraine:            'Київ, Україна'
    estonia:            'Таллінн, Естонія'
    france:             'Ніцца, Франція'
  fr:
    page_head:          '~'
    about_who_head:     '~'
    about_who_text:     '~'
    about_what_head:    '~'
    about_what_text:    '~'
    about_how_head:     '~'
    about_how_text:     '~'
    about_where_head:   '~'
    about_where_text:   '~'
    what_we_do_head:    '~'
    contact_head:       '~'
    contact_txt:        '~'
    logo_alt:           '~'
    big_head:           '~'
    ui_more_info:       '~'
    ui_nav_toggle:      '~'
    ui_about:           '~'
    ui_services:        '~'
    ui_team:            '~'
    ui_contact:         '~'
    service_head:       '~'
    service_it_head:    '~'
    service_it_txt:     '~'
    service_lab_head:   '~'
    service_lab_txt:    '~'
    service_auto_head:  '~'
    service_auto_txt:   '~'
    service_pbr_head:   '~'
    service_pbr_txt:    '~'
    team_head:          '~'
    team_txt:           '~'
    company_name_code:  'Erint Labs OÜ, 14034333'
    company_address1:   '6 rue Sepapaja'
    company_address2:   'EE-15551 Tallinn'
    company_address3:   'ESTONIE'
    ukraine:            'Kiev, Ukraine'
    estonia:            'Tallinn, Estonie'
    france:             'Nice, France'
  ru:
    page_head:          '~'
    about_who_head:     '~'
    about_who_text:     '~'
    about_what_head:    '~'
    about_what_text:    '~'
    about_how_head:     '~'
    about_how_text:     '~'
    about_where_head:   '~'
    about_where_text:   '~'
    what_we_do_head:    '~'
    contact_head:       '~'
    contact_txt:        '~'
    logo_alt:           '~'
    big_head:           '~'
    ui_more_info:       '~'
    ui_nav_toggle:      '~'
    ui_about:           '~'
    ui_services:        '~'
    ui_team:            '~'
    ui_contact:         '~'
    service_head:       '~'
    service_it_head:    '~'
    service_it_txt:     '~'
    service_lab_head:   '~'
    service_lab_txt:    '~'
    service_auto_head:  '~'
    service_auto_txt:   '~'
    service_pbr_head:   '~'
    service_pbr_txt:    '~'
    team_head:          '~'
    team_txt:           '~'
    company_name_code:  'ООО «Erint Labs OÜ», 14034333'
    company_address1:   'ул. Сепапая, д. 6'
    company_address2:   'г. Таллин, EE-15551'
    company_address3:   'ЭСТОНИЯ'
    ukraine:            'Киев, Украина'
    estonia:            'Таллин, Эстония'
    france:             'Ницца, Франция'
