# Site settings
title: ErintLabs OÜ
email: info@mail.erint.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

facebook_username: erintlabs
github_username: ErintLabs

# Build settings
markdown: kramdown

# Setting language flags
# https://sylvain.durand.tf/making-jekyll-multilingual/ refer to this
defaults:
  -
    scope:
      path: uk
    values:
      lang: uk
  -
    scope:
      path: en
    values:
      lang: en
  -
    scope:
      path: fr
    values:
      lang: fr
  -
    scope:
      path: ru
    values:
      lang: ru

# Translations table
# TODO: is there a way to make it a separate file pretty please?
# WARNING: for typographic discipline reasons, single quotation marks are NOT
# to be used like apostrophes. If your keyboard lacks the respective glyph,
# here you are I have a free Unicode apostrophe right for you: ’
t:
  en:
    page_head:          'ErintLabs — your bioinformatics partner'
    who_we_are_head:    'Who we are'
    who_we_are_txt:     'We are young distributed team, based in Ukraine, Estonia and France brought together by a vision of becoming pioneers in the emerging fields of bioinformatics, sustainable economy and clean energy.'
    what_we_do_head:    'What we can do'
    contact_head:       'Let’s Get In Touch!'
    contact_txt:        'Ready to start your next project with us? That’s great! Give us a call or send us an email and we will get back to you as soon as possible!'
    logo_alt:           'ErintLabs Logo'
    big_head:           'Your bioinformatics & biotechnology partner'
    ui_more_info:       'Find Out More'
    ui_nav_toggle:      'Toggle navigation'
    ui_about:           'About'
    ui_services:        'Services'
    ui_team:            'Our team'
    ui_contact:         'Contact'
    service_head:       'At Your Service'
    service_it_head:    'IT services for science'
    service_it_txt:     'Everything you may need from R computing to genome calculation.'
    service_lab_head:   'Custom Lab Equipment'
    service_lab_txt:    'Like spectral analyzers and Langmuir-Blodgett troughs.'
    service_auto_head:  'Smart Automation'
    service_auto_txt:   'Using modern technologies which can drastically reduce costs of your business.'
    service_pbr_head:   'Biophotoreactors'
    service_pbr_txt:    'Take our hand in journey to the eco future.'
    team_head:          'Get to know'
    team_txt:           'our team'
    company_name_code:  'Erint Labs OÜ, 14034333'
    company_address1:   '6 Sepapaja Str.'
    company_address2:   'Tallinn, EE-15551'
    company_address3:   'ESTONIA'
  uk:
    page_head:          '~'
    who_we_are_head:    '~'
    who_we_are_txt:     '~'
    what_we_do_head:    '~'
    contact_head:       '~'
    contact_txt:        '~'
    logo_alt:           '~'
    big_head:           '~'
    ui_more_info:       '~'
    ui_nav_toggle:      '~'
    ui_about:           '~'
    ui_services:        '~'
    ui_team:            '~'
    ui_contact:         '~'
    service_head:       '~'
    service_it_head:    '~'
    service_it_txt:     '~'
    service_lab_head:   '~'
    service_lab_txt:    '~'
    service_auto_head:  '~'
    service_auto_txt:   '~'
    service_pbr_head:   '~'
    service_pbr_txt:    '~'
    team_head:          '~'
    team_txt:           '~'
    company_name_code:  'ТОВ «Erint Labs OÜ», 14034333'
    company_address1:   'вул. Сепапая, буд. 6'
    company_address2:   'м. Таллінн, EE-15551'
    company_address3:   'ЕСТОНІЯ'
  fr:
    page_head:          '~'
    who_we_are_head:    '~'
    who_we_are_txt:     '~'
    what_we_do_head:    '~'
    contact_head:       '~'
    contact_txt:        '~'
    logo_alt:           '~'
    big_head:           '~'
    ui_more_info:       '~'
    ui_nav_toggle:      '~'
    ui_about:           '~'
    ui_services:        '~'
    ui_team:            '~'
    ui_contact:         '~'
    service_head:       '~'
    service_it_head:    '~'
    service_it_txt:     '~'
    service_lab_head:   '~'
    service_lab_txt:    '~'
    service_auto_head:  '~'
    service_auto_txt:   '~'
    service_pbr_head:   '~'
    service_pbr_txt:    '~'
    team_head:          '~'
    team_txt:           '~'
    company_name_code:  'Erint Labs OÜ, 14034333'
    company_address1:   '6 rue Sepapaja'
    company_address2:   'EE-15551 Tallinn'
    company_address3:   'ESTONIE'
  ru:
    page_head:          '~'
    who_we_are_head:    '~'
    who_we_are_txt:     '~'
    what_we_do_head:    '~'
    contact_head:       '~'
    contact_txt:        '~'
    logo_alt:           '~'
    big_head:           '~'
    ui_more_info:       '~'
    ui_nav_toggle:      '~'
    ui_about:           '~'
    ui_services:        '~'
    ui_team:            '~'
    ui_contact:         '~'
    service_head:       '~'
    service_it_head:    '~'
    service_it_txt:     '~'
    service_lab_head:   '~'
    service_lab_txt:    '~'
    service_auto_head:  '~'
    service_auto_txt:   '~'
    service_pbr_head:   '~'
    service_pbr_txt:    '~'
    team_head:          '~'
    team_txt:           '~'
    company_name_code:  'ООО «Erint Labs OÜ», 14034333'
    company_address1:   'ул. Сепапая, д. 6'
    company_address2:   'г. Таллин, EE-15551'
    company_address3:   'ЭСТОНИЯ'
